// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/mkhsnw/golang-starter-kit/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// ProductRepositoryInterface is an autogenerated mock type for the ProductRepositoryInterface type
type ProductRepositoryInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *ProductRepositoryInterface) Create(ctx context.Context, _a1 *entity.Product) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Product) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, _a1
func (_m *ProductRepositoryInterface) Delete(ctx context.Context, _a1 *entity.Product) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Product) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllCursor provides a mock function with given fields: ctx, cursor, size, preloads
func (_m *ProductRepositoryInterface) FindAllCursor(ctx context.Context, cursor uint64, size int, preloads ...string) ([]entity.Product, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, cursor, size)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindAllCursor")
	}

	var r0 []entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int, ...string) ([]entity.Product, error)); ok {
		return rf(ctx, cursor, size, preloads...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, int, ...string) []entity.Product); ok {
		r0 = rf(ctx, cursor, size, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, int, ...string) error); ok {
		r1 = rf(ctx, cursor, size, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllPaginated provides a mock function with given fields: ctx, page, size, preloads
func (_m *ProductRepositoryInterface) FindAllPaginated(ctx context.Context, page int, size int, preloads ...string) ([]entity.Product, int64, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, page, size)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginated")
	}

	var r0 []entity.Product
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, ...string) ([]entity.Product, int64, error)); ok {
		return rf(ctx, page, size, preloads...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, ...string) []entity.Product); ok {
		r0 = rf(ctx, page, size, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, ...string) int64); ok {
		r1 = rf(ctx, page, size, preloads...)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, ...string) error); ok {
		r2 = rf(ctx, page, size, preloads...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id, preloads
func (_m *ProductRepositoryInterface) FindByID(ctx context.Context, id interface{}, preloads ...string) (*entity.Product, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...string) (*entity.Product, error)); ok {
		return rf(ctx, id, preloads...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...string) *entity.Product); ok {
		r0 = rf(ctx, id, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, ...string) error); ok {
		r1 = rf(ctx, id, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *ProductRepositoryInterface) Update(ctx context.Context, _a1 *entity.Product) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Product) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductRepositoryInterface creates a new instance of ProductRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepositoryInterface {
	mock := &ProductRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
