// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryInterface is an autogenerated mock type for the RepositoryInterface type
type RepositoryInterface[T interface{}] struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, entity
func (_m *RepositoryInterface[T]) Create(ctx context.Context, entity *T) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, entity
func (_m *RepositoryInterface[T]) Delete(ctx context.Context, entity *T) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllCursor provides a mock function with given fields: ctx, cursor, size, preloads
func (_m *RepositoryInterface[T]) FindAllCursor(ctx context.Context, cursor string, size int, preloads ...string) ([]T, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, cursor, size)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindAllCursor")
	}

	var r0 []T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, ...string) ([]T, error)); ok {
		return rf(ctx, cursor, size, preloads...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, ...string) []T); ok {
		r0 = rf(ctx, cursor, size, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, ...string) error); ok {
		r1 = rf(ctx, cursor, size, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllPaginated provides a mock function with given fields: ctx, page, size, preloads
func (_m *RepositoryInterface[T]) FindAllPaginated(ctx context.Context, page int, size int, preloads ...string) ([]T, int64, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, page, size)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginated")
	}

	var r0 []T
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, ...string) ([]T, int64, error)); ok {
		return rf(ctx, page, size, preloads...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, ...string) []T); ok {
		r0 = rf(ctx, page, size, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, ...string) int64); ok {
		r1 = rf(ctx, page, size, preloads...)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, ...string) error); ok {
		r2 = rf(ctx, page, size, preloads...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id, preloads
func (_m *RepositoryInterface[T]) FindByID(ctx context.Context, id interface{}, preloads ...string) (*T, error) {
	_va := make([]interface{}, len(preloads))
	for _i := range preloads {
		_va[_i] = preloads[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...string) (*T, error)); ok {
		return rf(ctx, id, preloads...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, ...string) *T); ok {
		r0 = rf(ctx, id, preloads...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, ...string) error); ok {
		r1 = rf(ctx, id, preloads...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, entity
func (_m *RepositoryInterface[T]) Update(ctx context.Context, entity *T) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepositoryInterface creates a new instance of RepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryInterface[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryInterface[T] {
	mock := &RepositoryInterface[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
