package exception

const (
	USER_NOT_FOUND       = "USER_NOT_FOUND"
	NOT_FOUND            = "NOT_FOUND"
	EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
	INVALID_PASSWORD     = "INVALID_PASSWORD"
	TOKEN_EXPIRED        = "TOKEN_EXPIRED"
	INVALID_TOKEN        = "INVALID_TOKEN"
	UNAUTHORIZED         = "UNAUTHORIZED"
	FORBIDDEN            = "FORBIDDEN"
	VALIDATION_ERROR     = "VALIDATION_ERROR"
	DATABASE_ERROR       = "DATABASE_ERROR"
	INTERNAL_ERROR       = "INTERNAL_ERROR"
)
