// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mkhsnw/golang-starter-kit/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderUsecaseInterface is an autogenerated mock type for the OrderUsecaseInterface type
type OrderUsecaseInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *OrderUsecaseInterface) Create(ctx context.Context, req *model.CreateOrderRequest) (*model.OrderResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateOrderRequest) (*model.OrderResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateOrderRequest) *model.OrderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *OrderUsecaseInterface) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, cursor, size
func (_m *OrderUsecaseInterface) GetAll(ctx context.Context, cursor string, size int) ([]model.OrderResponse, *string, error) {
	ret := _m.Called(ctx, cursor, size)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.OrderResponse
	var r1 *string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]model.OrderResponse, *string, error)); ok {
		return rf(ctx, cursor, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []model.OrderResponse); ok {
		r0 = rf(ctx, cursor, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) *string); ok {
		r1 = rf(ctx, cursor, size)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*string)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int) error); ok {
		r2 = rf(ctx, cursor, size)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *OrderUsecaseInterface) GetByID(ctx context.Context, id string) (*model.OrderResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.OrderResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.OrderResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *OrderUsecaseInterface) Update(ctx context.Context, id string, req *model.UpdateOrderRequest) (*model.OrderResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.UpdateOrderRequest) (*model.OrderResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.UpdateOrderRequest) *model.OrderResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *model.UpdateOrderRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderUsecaseInterface creates a new instance of OrderUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderUsecaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderUsecaseInterface {
	mock := &OrderUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
