// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mkhsnw/golang-starter-kit/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ProductUsecaseInterface is an autogenerated mock type for the ProductUsecaseInterface type
type ProductUsecaseInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *ProductUsecaseInterface) Create(ctx context.Context, req *model.CreateProductRequest) (*model.ProductResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateProductRequest) (*model.ProductResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateProductRequest) *model.ProductResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateProductRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ProductUsecaseInterface) Delete(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, page, size
func (_m *ProductUsecaseInterface) GetAll(ctx context.Context, page int, size int) ([]model.ProductResponse, int64, error) {
	ret := _m.Called(ctx, page, size)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.ProductResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.ProductResponse, int64, error)); ok {
		return rf(ctx, page, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.ProductResponse); ok {
		r0 = rf(ctx, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, size)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, size)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ProductUsecaseInterface) GetByID(ctx context.Context, id uint64) (*model.ProductResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*model.ProductResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *model.ProductResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *ProductUsecaseInterface) Update(ctx context.Context, id uint64, req *model.UpdateProductRequest) (*model.ProductResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, *model.UpdateProductRequest) (*model.ProductResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, *model.UpdateProductRequest) *model.ProductResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, *model.UpdateProductRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductUsecaseInterface creates a new instance of ProductUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductUsecaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductUsecaseInterface {
	mock := &ProductUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
